# Generated by Django 3.2.5 on 2021-09-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_remove_leaddetails_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuser',
            name='is_available',
        ),
    ]
