# Generated by Django 3.2.5 on 2021-09-26 07:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_auto_20210926_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='leaddetails',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None),
        ),
    ]
