# Generated by Django 3.2.5 on 2021-09-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_auto_20210926_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuser',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='pic',
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
