# Generated by Django 3.2.5 on 2021-09-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_auto_20210929_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuser',
            name='email',
        ),
    ]
