# Generated by Django 3.2.5 on 2021-10-01 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0014_remove_agentuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddetails',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
