# Generated by Django 3.2.5 on 2021-10-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0015_leaddetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddetails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
