# Generated by Django 3.2.5 on 2021-10-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0016_alter_leaddetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='socialauth',
            field=models.BooleanField(default=True),
        ),
    ]
