# Generated by Django 3.2.5 on 2021-10-06 14:16

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0017_user_socialauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddetails',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VechileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=15)),
                ('licencepic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Rcpic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Rigestration_Number', models.CharField(max_length=15, unique=True)),
                ('licenseuser', models.CharField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None)),
                ('lead', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='claims.leaddetails')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('UID', models.CharField(max_length=20, unique=True)),
                ('Pdate', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='claims.leaddetails')),
            ],
        ),
    ]
