# Generated by Django 3.2.5 on 2021-10-08 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0018_auto_20211006_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectdetails',
            name='Pdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
