# Generated by Django 3.2.5 on 2021-10-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0019_alter_objectdetails_pdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddetails',
            name='is_v',
            field=models.BooleanField(default=True),
        ),
    ]
