# Generated by Django 3.2.5 on 2021-10-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0020_leaddetails_is_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechiledetails',
            name='Rcpic',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vechiledetails',
            name='licencepic',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
