# Generated by Django 3.2.5 on 2021-10-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0021_auto_20211009_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='discribtion',
        ),
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
